#!/bin/sh

if test z$1 = z; then
    echo "USAGE: package.sh <pkgdir>"
    echo "This should only be used by invoking \"make package\", and then"
    echo "only on Windows or other non-UNIX platforms."
fi

PKGDIR=$1
OS=`uname -s | sed -e 's:[_-].*$::'`

if test z$OS = zMINGW; then
EXE=.exe
else
EXE=
fi

rm -rf $PKGDIR
mkdir -pm 0755 $PKGDIR
cp -rf mod/* $PKGDIR
cp waspvm$EXE $PKGDIR
cd $PKGDIR

cat >site/config.ms <<EOF
;;; Generated by package.sh
(set-site-config! 'stub-path ".")
(set-site-config! 'bin-path ".")
(set-site-config! 'mod-path '("."))
EOF

../waspc$EXE -exe waspc$EXE   -stub waspvm$EXE bin/waspc
../waspc$EXE -exe wasp$EXE    -stub waspvm$EXE bin/wasp

## TODO: This is bogus..
if test z$EXE = z.exe; then
    ../waspc -exe waspdoc$EXE -stub waspvm$EXE bin/waspdoc
fi

