#!/bin/sh

rm -rf package
mkdir -pm 0755 package
cp -rf mod/* package
cp wasp* package
cd package

cat >site/config.ms <<EOF
;;; Generated by package.sh
(set-site-config! 'stub-path ".")
(set-site-config! 'bin-path ".")
(set-site-config! 'mod-path '("."))
EOF

../waspc -exe waspc.exe   -stub waspvm.exe bin/waspc
../waspc -exe wasp.exe    -stub waspvm.exe bin/wasp
../waspc -exe waspdoc.exe -stub waspvm.exe bin/waspdoc

